// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcrRUoyOyHtQiDTKPWrM178u43KGKzvX8',
    appId: '1:643109720518:web:8b8ce998c87e25d7b3e2c7',
    messagingSenderId: '643109720518',
    projectId: 'customerloop-4b038',
    authDomain: 'customerloop-4b038.firebaseapp.com',
    storageBucket: 'customerloop-4b038.firebasestorage.app',
    measurementId: 'G-VKGHJ4T0RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGXaGByuR7y7A5thhlDUUI-jSojlKWLUI',
    appId: '1:643109720518:android:b542879a6b6772fdb3e2c7',
    messagingSenderId: '643109720518',
    projectId: 'customerloop-4b038',
    storageBucket: 'customerloop-4b038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMx7nby-GltITR3Hn2ayEpimxABzvbCFk',
    appId: '1:643109720518:ios:12ad5237b0b315b5b3e2c7',
    messagingSenderId: '643109720518',
    projectId: 'customerloop-4b038',
    storageBucket: 'customerloop-4b038.firebasestorage.app',
    iosBundleId: 'com.example.customerloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMx7nby-GltITR3Hn2ayEpimxABzvbCFk',
    appId: '1:643109720518:ios:12ad5237b0b315b5b3e2c7',
    messagingSenderId: '643109720518',
    projectId: 'customerloop-4b038',
    storageBucket: 'customerloop-4b038.firebasestorage.app',
    iosBundleId: 'com.example.customerloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcrRUoyOyHtQiDTKPWrM178u43KGKzvX8',
    appId: '1:643109720518:web:9c792a23909297dcb3e2c7',
    messagingSenderId: '643109720518',
    projectId: 'customerloop-4b038',
    authDomain: 'customerloop-4b038.firebaseapp.com',
    storageBucket: 'customerloop-4b038.firebasestorage.app',
    measurementId: 'G-LZFZ8LQVWG',
  );

}