// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU3kQK0a5k_6Gus3tfaMzyiy1Bk5lBH4M',
    appId: '1:556266555913:web:b7c517f4eebe35a45246d8',
    messagingSenderId: '556266555913',
    projectId: 'customer-57248',
    authDomain: 'customer-57248.firebaseapp.com',
    storageBucket: 'customer-57248.firebasestorage.app',
    measurementId: 'G-PJ0CWFPSP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPO7HQ2W2VmJslCjhKPVrbJOQCNQ0_vko',
    appId: '1:556266555913:android:a5d0be0a8a45428f5246d8',
    messagingSenderId: '556266555913',
    projectId: 'customer-57248',
    storageBucket: 'customer-57248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB846dWtyM9oHG9_arZ8UX7DdxTIHypcqI',
    appId: '1:556266555913:ios:0127d03ba7caf9a05246d8',
    messagingSenderId: '556266555913',
    projectId: 'customer-57248',
    storageBucket: 'customer-57248.firebasestorage.app',
    iosBundleId: 'com.example.customerloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB846dWtyM9oHG9_arZ8UX7DdxTIHypcqI',
    appId: '1:556266555913:ios:0127d03ba7caf9a05246d8',
    messagingSenderId: '556266555913',
    projectId: 'customer-57248',
    storageBucket: 'customer-57248.firebasestorage.app',
    iosBundleId: 'com.example.customerloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU3kQK0a5k_6Gus3tfaMzyiy1Bk5lBH4M',
    appId: '1:556266555913:web:5d43fed1e50d793c5246d8',
    messagingSenderId: '556266555913',
    projectId: 'customer-57248',
    authDomain: 'customer-57248.firebaseapp.com',
    storageBucket: 'customer-57248.firebasestorage.app',
    measurementId: 'G-5GTKDWFXD9',
  );
}
